# -*- coding: utf-8 -*-
"""quiz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Emillka/Learn-Python/blob/main/quiz.ipynb
"""

import json

points = 0

def show_question(question):
    global points
    print()
    print(question["question"])
    print("a:", question["a"])
    print("b:", question["b"])
    print("c:", question["c"])
    print("d:", question["d"])
    print()

    answer = input("Which answer do you choose? ")
    if answer == question["correct_answer"]:
        points += 1
        print("That's the correct answer! Well done! You now have", points, "points.")
    else:
        print("Unfortunately, that's the wrong answer. The correct answer is", question["correct_answer"], ".")

# Quiz data as a JSON string
quiz_data = '''
[
  {
    "question": "In which year was the State Fire Service established in Poland?",
    "a": 1992,
    "b": 1894,
    "c": 2000,
    "d": 2002,
    "correct_answer": "a"
  },
  {
    "question": "How many County/Municipal Fire Service Commands operate in Poland?",
    "a": 90,
    "b": 219,
    "c": 432,
    "d": 335,
    "correct_answer": "d"
  },
  {
    "question": "What does the abbreviation GBA stand for?",
    "a": "Light fire truck with a water tank",
    "b": "Medium fire truck",
    "c": "Heavy fire truck",
    "d": "Hydraulic lift",
    "correct_answer": "b"
  }
]
'''

# Load JSON data
questions = json.loads(quiz_data)

# Execute the quiz
for i in range(0, len(questions)):
    show_question(questions[i])

print()
print("The game is over, the number of points scored is " + str(points) + ".")